ExternalProject_Add(
	CArL-EP
	DOWNLOAD_COMMAND ""
	CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR> -DCMAKE_PREFIX_PATH=<INSTALL_DIR> -DBUILD_STATIC=ON -DUSE_BLISS=ON -DUSE_COCOA=ON -DEXPORT_TO_CMAKE=OFF
	BUILD_COMMAND ${CMAKE_MAKE_PROGRAM} lib_carl lib_carl_static
	INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install/fast
)
