#!/usr/bin/env bash

# This script can be called on smt2-files on which an assertion fails. 
# TODO untested!

# Usage ddsmt-assertion <in.smt2> <out.smt2> <solver>

ERROR=$($3 $1 2>&1 >/dev/null)
echo $ERROR
ddsmt -j8 -v --match-err "$ERROR" $1 $2 $3