/**
 * @file   config.h
 * @author Ulrich Loup
 *
 * @since January 29, 2013, 4:27 PM
 * @version 2013-05-29
 */
#ifndef SMTRAT_CADCONFIG_H
#define SMTRAT_CADCONFIG_H

#define SMTRAT_CAD_VARIABLEBOUNDS

#define SMTRAT_CADSETTING_1
/* #undef SMTRAT_CADSETTING_2 */
/* #undef SMTRAT_CADSETTING_3 */
/* #undef SMTRAT_CADSETTING_4 */
/* #undef SMTRAT_CADSETTING_5 */
/* #undef SMTRAT_CADSETTING_6 */
/* #undef SMTRAT_CADSETTING_7 */
/* #undef SMTRAT_CADSETTING_8 */
/* #undef SMTRAT_CADSETTING_9 */

#ifdef SMTRAT_CADSETTING_1
// default
#endif
#ifdef SMTRAT_CADSETTING_2
#define SMTRAT_CAD_DISABLE_SMT
#endif
#ifdef SMTRAT_CADSETTING_3
#define SMTRAT_CAD_DISABLEEQUATIONDETECT_SETTING
#define SMTRAT_CAD_DISABLE_SMT
#endif
#ifdef SMTRAT_CADSETTING_4
#define SMTRAT_CAD_ALTERNATIVE_SETTING
#endif
#ifdef SMTRAT_CADSETTING_5
#define SMTRAT_CAD_DISABLE_THEORYPROPAGATION
#endif
#ifdef SMTRAT_CADSETTING_6
#define SMTRAT_CAD_DISABLE_MIS
#endif
#ifdef SMTRAT_CADSETTING_7
#define SMTRAT_CAD_DISABLE_PROJECTIONORDEROPTIMIZATION
#endif
#ifdef SMTRAT_CADSETTING_8
#define SMTRAT_CAD_ONEMOSTDEGREEVERTEX_MISHEURISTIC
#endif
#ifdef SMTRAT_CADSETTING_9
#define SMTRAT_CAD_TWOMOSTDEGREEVERTICES_MISHEURISTIC
#endif

#endif // SMTRAT_CADCONFIG_H
