#include "CompileInfo.h"

namespace smtrat 
{

const std::string CompileInfo::SystemName = "Linux";
const std::string CompileInfo::SystemVersion = "4.15.0-45-generic";
const std::string CompileInfo::BuildType = "DEBUG";
const std::string CompileInfo::CXXCompiler = "/usr/bin/g++-7";
const std::string CompileInfo::CXXCompilerVersion = "7.3.0";
const std::string CompileInfo::GitRevisionSHA1 = "cb64a52d333129f361906d9d655054eb1cf642c8";
const std::string CompileInfo::PackageName = "smtrat";
const std::string CompileInfo::ProjectName = "SMT-RAT";
const std::string CompileInfo::Version = "18.12.122";
const std::string CompileInfo::Website = "https://github.com/smtrat/smtrat/wiki";
const std::string CompileInfo::GitVersion = "18.12.122-gcb64a52d";

std::ostream& operator<<(std::ostream& os, CMakeOptionPrinter cmop) {
	auto print = [&os,&cmop](bool advanced, const std::string& type, const std::string& key, const std::string& value) {
		if (advanced && !cmop.advanced) return;
		if (type.empty()) return;
		if (key.empty()) return;
		if (key[0] == '_') return;
		if (value.find('\n') == std::string::npos) {
			os << key << " = " << value << std::endl;
		} else {
			os << key << " has multiple lines." << std::endl;
		}
	};

	
	print(0, "STRING", "ADDITIONAL_INCLUDE_DIRS", R"VAR()VAR");
	print(0, "STRING", "ADDITIONAL_LINK_DIRS", R"VAR()VAR");
	print(0, "BOOL", "BENCHMAX_DATABASE", R"VAR(OFF)VAR");
	print(0, "BOOL", "BENCHMAX_LOGGING", R"VAR(ON)VAR");
	print(0, "BOOL", "BENCHMAX_USE_SMTPARSER", R"VAR(OFF)VAR");
	print(1, "FILEPATH", "BIBER_COMPILER", R"VAR(BIBER_COMPILER-NOTFOUND)VAR");
	print(1, "FILEPATH", "BIBTEX_COMPILER", R"VAR(/usr/bin/bibtex)VAR");
	print(0, "", "BIN_INSTALL_DIR", R"VAR(/usr/local/)VAR");
	print(0, "BOOL", "BUILD_GUI", R"VAR(OFF)VAR");
	print(0, "BOOL", "BUILD_SOLVER", R"VAR(ON)VAR");
	print(0, "", "CARL_BUILD_DOXYGEN", R"VAR(OFF)VAR");
	print(0, "", "CARL_FORCE_SHIPPED_GMP", R"VAR(OFF)VAR");
	print(0, "", "CARL_FORCE_SHIPPED_RESOURCES", R"VAR(OFF)VAR");
	print(0, "", "CARL_LOGGING", R"VAR(OFF)VAR");
	print(0, "", "CARL_REQUIRED_VERSION", R"VAR(18.11)VAR");
	print(0, "", "CARL_THREAD_SAFE", R"VAR(OFF)VAR");
	print(0, "", "CARL_TIMING", R"VAR(OFF)VAR");
	print(0, "", "CARL_USE_BLISS", R"VAR(OFF)VAR");
	print(0, "", "CARL_USE_CLN_NUMBERS", R"VAR(OFF)VAR");
	print(0, "", "CARL_USE_COCOA", R"VAR(OFF)VAR");
	print(0, "", "CARL_USE_GINAC", R"VAR(OFF)VAR");
	print(0, "", "CARL_USE_MPFR_FLOAT", R"VAR(OFF)VAR");
	print(0, "", "CARL_VERSION_FILE", R"VAR(/home/jasper/i2HiWi/code/smtrat/resources/carl-required.version)VAR");
	print(0, "FILEPATH", "CLANG_TIDY", R"VAR(CLANG_TIDY-NOTFOUND)VAR");
	print(0, "BOOL", "CLI_ENABLE_DIMACS_PARSER", R"VAR(OFF)VAR");
	print(0, "BOOL", "CLI_ENABLE_FORMULAPARSER", R"VAR(OFF)VAR");
	print(0, "BOOL", "CLI_ENABLE_OPB_PARSER", R"VAR(OFF)VAR");
	print(0, "BOOL", "CLI_ENABLE_PREPROCESSOR", R"VAR(ON)VAR");
	print(0, "BOOL", "CLI_ENABLE_QE", R"VAR(OFF)VAR");
	print(1, "FILEPATH", "CMAKE_AR", R"VAR(/usr/bin/ar)VAR");
	print(1, "FILEPATH", "CMAKE_AR", R"VAR(/usr/bin/ar)VAR");
	print(0, "", "CMAKE_AUTOMOC_COMPILER_PREDEFINES", R"VAR(ON)VAR");
	print(0, "", "CMAKE_AUTOMOC_MACRO_NAMES", R"VAR(Q_OBJECT;Q_GADGET;Q_NAMESPACE)VAR");
	print(0, "", "CMAKE_BASE_NAME", R"VAR(g++)VAR");
	print(0, "", "CMAKE_BINARY_DIR", R"VAR(/home/jasper/i2HiWi/code/smtrat/build)VAR");
	print(0, "", "CMAKE_BUILD_TOOL", R"VAR(/usr/bin/make)VAR");
	print(0, "STRING", "CMAKE_BUILD_TYPE", R"VAR(DEBUG)VAR");
	print(0, "STRING", "CMAKE_BUILD_TYPE", R"VAR(DEBUG)VAR");
	print(0, "INTERNAL", "CMAKE_CACHEFILE_DIR", R"VAR(/home/jasper/i2HiWi/code/smtrat/build)VAR");
	print(0, "INTERNAL", "CMAKE_CACHE_MAJOR_VERSION", R"VAR(3)VAR");
	print(0, "INTERNAL", "CMAKE_CACHE_MINOR_VERSION", R"VAR(10)VAR");
	print(0, "INTERNAL", "CMAKE_CACHE_PATCH_VERSION", R"VAR(2)VAR");
	print(0, "", "CMAKE_CFG_INTDIR", R"VAR(.)VAR");
	print(1, "BOOL", "CMAKE_COLOR_MAKEFILE", R"VAR(ON)VAR");
	print(0, "INTERNAL", "CMAKE_COMMAND", R"VAR(/usr/bin/cmake)VAR");
	print(0, "", "CMAKE_COMPILER_IS_GNUCXX", R"VAR(1)VAR");
	print(0, "INTERNAL", "CMAKE_CPACK_COMMAND", R"VAR(/usr/bin/cpack)VAR");
	print(0, "", "CMAKE_CROSSCOMPILING", R"VAR(FALSE)VAR");
	print(0, "INTERNAL", "CMAKE_CTEST_COMMAND", R"VAR(/usr/bin/ctest)VAR");
	print(0, "", "CMAKE_CUDA_IMPLICIT_INCLUDE_DIRECTORIES", R"VAR(/usr/include)VAR");
	print(0, "", "CMAKE_CURRENT_BINARY_DIR", R"VAR(/home/jasper/i2HiWi/code/smtrat/build/src/smtrat-common)VAR");
	print(0, "", "CMAKE_CURRENT_LIST_DIR", R"VAR(/home/jasper/i2HiWi/code/smtrat/src/smtrat-common)VAR");
	print(0, "", "CMAKE_CURRENT_LIST_FILE", R"VAR(/home/jasper/i2HiWi/code/smtrat/src/smtrat-common/CMakeLists.txt)VAR");
	print(0, "", "CMAKE_CURRENT_SOURCE_DIR", R"VAR(/home/jasper/i2HiWi/code/smtrat/src/smtrat-common)VAR");
	print(0, "", "CMAKE_CXX11_COMPILE_FEATURES", R"VAR(cxx_std_11;cxx_alias_templates;cxx_alignas;cxx_alignof;cxx_attributes;cxx_auto_type;cxx_constexpr;cxx_decltype;cxx_decltype_incomplete_return_types;cxx_default_function_template_args;cxx_defaulted_functions;cxx_defaulted_move_initializers;cxx_delegating_constructors;cxx_deleted_functions;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_extended_friend_declarations;cxx_extern_templates;cxx_final;cxx_func_identifier;cxx_generalized_initializers;cxx_inheriting_constructors;cxx_inline_namespaces;cxx_lambdas;cxx_local_type_template_args;cxx_long_long_type;cxx_noexcept;cxx_nonstatic_member_init;cxx_nullptr;cxx_override;cxx_range_for;cxx_raw_string_literals;cxx_reference_qualified_functions;cxx_right_angle_brackets;cxx_rvalue_references;cxx_sizeof_member;cxx_static_assert;cxx_strong_enums;cxx_thread_local;cxx_trailing_return_types;cxx_unicode_literals;cxx_uniform_initialization;cxx_unrestricted_unions;cxx_user_literals;cxx_variadic_macros;cxx_variadic_templates)VAR");
	print(0, "", "CMAKE_CXX11_EXTENSION_COMPILE_OPTION", R"VAR(-std=gnu++11)VAR");
	print(0, "", "CMAKE_CXX11_STANDARD_COMPILE_OPTION", R"VAR(-std=c++11)VAR");
	print(0, "", "CMAKE_CXX14_COMPILE_FEATURES", R"VAR(cxx_std_14;cxx_aggregate_default_initializers;cxx_attribute_deprecated;cxx_binary_literals;cxx_contextual_conversions;cxx_decltype_auto;cxx_digit_separators;cxx_generic_lambdas;cxx_lambda_init_captures;cxx_relaxed_constexpr;cxx_return_type_deduction;cxx_variable_templates)VAR");
	print(0, "", "CMAKE_CXX14_EXTENSION_COMPILE_OPTION", R"VAR(-std=gnu++14)VAR");
	print(0, "", "CMAKE_CXX14_STANDARD_COMPILE_OPTION", R"VAR(-std=c++14)VAR");
	print(0, "", "CMAKE_CXX17_COMPILE_FEATURES", R"VAR(cxx_std_17)VAR");
	print(0, "", "CMAKE_CXX17_EXTENSION_COMPILE_OPTION", R"VAR(-std=gnu++1z)VAR");
	print(0, "", "CMAKE_CXX17_STANDARD_COMPILE_OPTION", R"VAR(-std=c++1z)VAR");
	print(0, "", "CMAKE_CXX98_COMPILE_FEATURES", R"VAR(cxx_std_98;cxx_template_template_parameters)VAR");
	print(0, "", "CMAKE_CXX98_EXTENSION_COMPILE_OPTION", R"VAR(-std=gnu++98)VAR");
	print(0, "", "CMAKE_CXX98_STANDARD_COMPILE_OPTION", R"VAR(-std=c++98)VAR");
	print(0, "", "CMAKE_CXX_ABI_COMPILED", R"VAR(TRUE)VAR");
	print(0, "", "CMAKE_CXX_ARCHIVE_APPEND", R"VAR(<CMAKE_AR> q  <TARGET> <LINK_FLAGS> <OBJECTS>)VAR");
	print(0, "", "CMAKE_CXX_ARCHIVE_APPEND_IPO", R"VAR("/usr/bin/gcc-ar-7" r <TARGET> <LINK_FLAGS> <OBJECTS>)VAR");
	print(0, "", "CMAKE_CXX_ARCHIVE_CREATE", R"VAR(<CMAKE_AR> qc <TARGET> <LINK_FLAGS> <OBJECTS>)VAR");
	print(0, "", "CMAKE_CXX_ARCHIVE_CREATE_IPO", R"VAR("/usr/bin/gcc-ar-7" cr <TARGET> <LINK_FLAGS> <OBJECTS>)VAR");
	print(0, "", "CMAKE_CXX_ARCHIVE_FINISH", R"VAR(<CMAKE_RANLIB> <TARGET>)VAR");
	print(0, "", "CMAKE_CXX_ARCHIVE_FINISH_IPO", R"VAR("/usr/bin/gcc-ranlib-7" <TARGET>)VAR");
	print(0, "", "CMAKE_CXX_CL_SHOWINCLUDES_PREFIX", R"VAR()VAR");
	print(1, "STRING", "CMAKE_CXX_COMPILER", R"VAR(/usr/bin/g++-7)VAR");
	print(1, "STRING", "CMAKE_CXX_COMPILER", R"VAR(/usr/bin/g++-7)VAR");
	print(0, "", "CMAKE_CXX_COMPILER_ABI", R"VAR(ELF)VAR");
	print(1, "FILEPATH", "CMAKE_CXX_COMPILER_AR", R"VAR(/usr/bin/gcc-ar-7)VAR");
	print(1, "FILEPATH", "CMAKE_CXX_COMPILER_AR", R"VAR(/usr/bin/gcc-ar-7)VAR");
	print(0, "", "CMAKE_CXX_COMPILER_ARG1", R"VAR()VAR");
	print(0, "", "CMAKE_CXX_COMPILER_ENV_VAR", R"VAR(CXX)VAR");
	print(0, "", "CMAKE_CXX_COMPILER_ID", R"VAR(GNU)VAR");
	print(0, "", "CMAKE_CXX_COMPILER_ID_RUN", R"VAR(1)VAR");
	print(0, "", "CMAKE_CXX_COMPILER_LOADED", R"VAR(1)VAR");
	print(0, "", "CMAKE_CXX_COMPILER_PREDEFINES_COMMAND", R"VAR(/usr/bin/g++-7;-dM;-E;-c;/usr/share/cmake-3.10/Modules/CMakeCXXCompilerABI.cpp)VAR");
	print(1, "FILEPATH", "CMAKE_CXX_COMPILER_RANLIB", R"VAR(/usr/bin/gcc-ranlib-7)VAR");
	print(1, "FILEPATH", "CMAKE_CXX_COMPILER_RANLIB", R"VAR(/usr/bin/gcc-ranlib-7)VAR");
	print(0, "", "CMAKE_CXX_COMPILER_VERSION", R"VAR(7.3.0)VAR");
	print(0, "", "CMAKE_CXX_COMPILER_VERSION_INTERNAL", R"VAR()VAR");
	print(0, "", "CMAKE_CXX_COMPILER_WORKS", R"VAR(TRUE)VAR");
	print(0, "", "CMAKE_CXX_COMPILER_WRAPPER", R"VAR()VAR");
	print(0, "", "CMAKE_CXX_COMPILE_FEATURES", R"VAR(cxx_std_98;cxx_template_template_parameters;cxx_std_11;cxx_alias_templates;cxx_alignas;cxx_alignof;cxx_attributes;cxx_auto_type;cxx_constexpr;cxx_decltype;cxx_decltype_incomplete_return_types;cxx_default_function_template_args;cxx_defaulted_functions;cxx_defaulted_move_initializers;cxx_delegating_constructors;cxx_deleted_functions;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_extended_friend_declarations;cxx_extern_templates;cxx_final;cxx_func_identifier;cxx_generalized_initializers;cxx_inheriting_constructors;cxx_inline_namespaces;cxx_lambdas;cxx_local_type_template_args;cxx_long_long_type;cxx_noexcept;cxx_nonstatic_member_init;cxx_nullptr;cxx_override;cxx_range_for;cxx_raw_string_literals;cxx_reference_qualified_functions;cxx_right_angle_brackets;cxx_rvalue_references;cxx_sizeof_member;cxx_static_assert;cxx_strong_enums;cxx_thread_local;cxx_trailing_return_types;cxx_unicode_literals;cxx_uniform_initialization;cxx_unrestricted_unions;cxx_user_literals;cxx_variadic_macros;cxx_variadic_templates;cxx_std_14;cxx_aggregate_default_initializers;cxx_attribute_deprecated;cxx_binary_literals;cxx_contextual_conversions;cxx_decltype_auto;cxx_digit_separators;cxx_generic_lambdas;cxx_lambda_init_captures;cxx_relaxed_constexpr;cxx_return_type_deduction;cxx_variable_templates;cxx_std_17)VAR");
	print(0, "", "CMAKE_CXX_COMPILE_OBJECT", R"VAR(<CMAKE_CXX_COMPILER>  <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT> -c <SOURCE>)VAR");
	print(0, "", "CMAKE_CXX_COMPILE_OPTIONS_IPO", R"VAR(-flto;-fno-fat-lto-objects)VAR");
	print(0, "", "CMAKE_CXX_COMPILE_OPTIONS_PIC", R"VAR(-fPIC)VAR");
	print(0, "", "CMAKE_CXX_COMPILE_OPTIONS_PIE", R"VAR(-fPIE)VAR");
	print(0, "", "CMAKE_CXX_COMPILE_OPTIONS_SYSROOT", R"VAR(--sysroot=)VAR");
	print(0, "", "CMAKE_CXX_COMPILE_OPTIONS_VISIBILITY", R"VAR(-fvisibility=)VAR");
	print(0, "", "CMAKE_CXX_COMPILE_OPTIONS_VISIBILITY_INLINES_HIDDEN", R"VAR(-fvisibility-inlines-hidden)VAR");
	print(0, "", "CMAKE_CXX_CREATE_ASSEMBLY_SOURCE", R"VAR(<CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -S <SOURCE> -o <ASSEMBLY_SOURCE>)VAR");
	print(0, "", "CMAKE_CXX_CREATE_PREPROCESSED_SOURCE", R"VAR(<CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -E <SOURCE> > <PREPROCESSED_SOURCE>)VAR");
	print(0, "", "CMAKE_CXX_CREATE_SHARED_LIBRARY", R"VAR(<CMAKE_CXX_COMPILER> <CMAKE_SHARED_LIBRARY_CXX_FLAGS> <LANGUAGE_COMPILE_FLAGS> <LINK_FLAGS> <CMAKE_SHARED_LIBRARY_CREATE_CXX_FLAGS> <SONAME_FLAG><TARGET_SONAME> -o <TARGET> <OBJECTS> <LINK_LIBRARIES>)VAR");
	print(0, "", "CMAKE_CXX_CREATE_SHARED_MODULE", R"VAR(<CMAKE_CXX_COMPILER> <CMAKE_SHARED_LIBRARY_CXX_FLAGS> <LANGUAGE_COMPILE_FLAGS> <LINK_FLAGS> <CMAKE_SHARED_LIBRARY_CREATE_CXX_FLAGS> <SONAME_FLAG><TARGET_SONAME> -o <TARGET> <OBJECTS> <LINK_LIBRARIES>)VAR");
	print(1, "STRING", "CMAKE_CXX_FLAGS", R"VAR( -Wunknown-pragmas -std=c++17 -pthread -fmax-errors=5 -fdiagnostics-color=auto -Wall -Wextra -Wconversion -Wno-deprecated-declarations -DDEBUG -ftemplate-backtrace-limit=0)VAR");
	print(1, "STRING", "CMAKE_CXX_FLAGS", R"VAR( -Wunknown-pragmas -std=c++17 -pthread -fmax-errors=5 -fdiagnostics-color=auto -Wall -Wextra -Wconversion -Wno-deprecated-declarations -DDEBUG -ftemplate-backtrace-limit=0)VAR");
	print(1, "STRING", "CMAKE_CXX_FLAGS_DEBUG", R"VAR(-g -O1)VAR");
	print(1, "STRING", "CMAKE_CXX_FLAGS_DEBUG", R"VAR(-g -O1)VAR");
	print(0, "", "CMAKE_CXX_FLAGS_DEBUG_INIT", R"VAR(-g)VAR");
	print(0, "", "CMAKE_CXX_FLAGS_INIT", R"VAR()VAR");
	print(1, "STRING", "CMAKE_CXX_FLAGS_MINSIZEREL", R"VAR(-Os -DNDEBUG)VAR");
	print(0, "", "CMAKE_CXX_FLAGS_MINSIZEREL_INIT", R"VAR(-Os -DNDEBUG)VAR");
	print(1, "STRING", "CMAKE_CXX_FLAGS_RELEASE", R"VAR(-O3 -DNDEBUG -O3)VAR");
	print(1, "STRING", "CMAKE_CXX_FLAGS_RELEASE", R"VAR(-O3 -DNDEBUG -O3)VAR");
	print(0, "", "CMAKE_CXX_FLAGS_RELEASE_INIT", R"VAR(-O3 -DNDEBUG)VAR");
	print(1, "STRING", "CMAKE_CXX_FLAGS_RELWITHDEBINFO", R"VAR(-O2 -g -DNDEBUG)VAR");
	print(0, "", "CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT", R"VAR(-O2 -g -DNDEBUG)VAR");
	print(0, "", "CMAKE_CXX_IGNORE_EXTENSIONS", R"VAR(inl;h;hpp;HPP;H;o;O;obj;OBJ;def;DEF;rc;RC)VAR");
	print(0, "", "CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES", R"VAR(/usr/include)VAR");
	print(0, "", "CMAKE_CXX_IMPLICIT_LINK_DIRECTORIES", R"VAR(/usr/lib/gcc/x86_64-linux-gnu/7;/usr/lib/x86_64-linux-gnu;/usr/lib;/lib/x86_64-linux-gnu;/lib)VAR");
	print(0, "", "CMAKE_CXX_IMPLICIT_LINK_FRAMEWORK_DIRECTORIES", R"VAR()VAR");
	print(0, "", "CMAKE_CXX_IMPLICIT_LINK_LIBRARIES", R"VAR(stdc++;m;gcc_s;gcc;c;gcc_s;gcc)VAR");
	print(0, "", "CMAKE_CXX_INFORMATION_LOADED", R"VAR(1)VAR");
	print(0, "", "CMAKE_CXX_LIBRARY_ARCHITECTURE", R"VAR(x86_64-linux-gnu)VAR");
	print(0, "", "CMAKE_CXX_LINKER_PREFERENCE", R"VAR(30)VAR");
	print(0, "", "CMAKE_CXX_LINKER_PREFERENCE_PROPAGATES", R"VAR(1)VAR");
	print(0, "", "CMAKE_CXX_LINK_EXECUTABLE", R"VAR(<CMAKE_CXX_COMPILER>  <FLAGS> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS>  -o <TARGET> <LINK_LIBRARIES>)VAR");
	print(0, "", "CMAKE_CXX_OUTPUT_EXTENSION", R"VAR(.o)VAR");
	print(0, "", "CMAKE_CXX_PLATFORM_ID", R"VAR(Linux)VAR");
	print(0, "", "CMAKE_CXX_SIMULATE_ID", R"VAR()VAR");
	print(0, "", "CMAKE_CXX_SIMULATE_VERSION", R"VAR()VAR");
	print(0, "", "CMAKE_CXX_SIZEOF_DATA_PTR", R"VAR(8)VAR");
	print(0, "", "CMAKE_CXX_SOURCE_FILE_EXTENSIONS", R"VAR(C;M;c++;cc;cpp;cxx;mm;CPP)VAR");
	print(0, "", "CMAKE_CXX_STANDARD_COMPUTED_DEFAULT", R"VAR(14)VAR");
	print(0, "", "CMAKE_CXX_STANDARD_DEFAULT", R"VAR(14)VAR");
	print(0, "", "CMAKE_CXX_VERBOSE_FLAG", R"VAR(-v)VAR");
	print(0, "", "CMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES", R"VAR(/usr/include)VAR");
	print(0, "", "CMAKE_DEPFILE_FLAGS_CXX", R"VAR(-MD -MT <OBJECT> -MF <DEPFILE>)VAR");
	print(0, "", "CMAKE_DL_LIBS", R"VAR(dl)VAR");
	print(0, "INTERNAL", "CMAKE_EDIT_COMMAND", R"VAR(/usr/bin/ccmake)VAR");
	print(0, "INTERNAL", "CMAKE_EXECUTABLE_FORMAT", R"VAR(ELF)VAR");
	print(0, "", "CMAKE_EXECUTABLE_RPATH_LINK_CXX_FLAG", R"VAR(-Wl,-rpath-link,)VAR");
	print(0, "", "CMAKE_EXECUTABLE_RUNTIME_CXX_FLAG", R"VAR(-Wl,-rpath,)VAR");
	print(0, "", "CMAKE_EXECUTABLE_RUNTIME_CXX_FLAG_SEP", R"VAR(:)VAR");
	print(0, "", "CMAKE_EXECUTABLE_SUFFIX", R"VAR()VAR");
	print(0, "", "CMAKE_EXE_EXPORTS_CXX_FLAG", R"VAR(-Wl,--export-dynamic)VAR");
	print(0, "", "CMAKE_EXE_EXPORTS_C_FLAG", R"VAR(-Wl,--export-dynamic)VAR");
	print(1, "STRING", "CMAKE_EXE_LINKER_FLAGS", R"VAR()VAR");
	print(1, "STRING", "CMAKE_EXE_LINKER_FLAGS_DEBUG", R"VAR()VAR");
	print(0, "", "CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT", R"VAR()VAR");
	print(0, "", "CMAKE_EXE_LINKER_FLAGS_INIT", R"VAR()VAR");
	print(1, "STRING", "CMAKE_EXE_LINKER_FLAGS_MINSIZEREL", R"VAR()VAR");
	print(0, "", "CMAKE_EXE_LINKER_FLAGS_MINSIZEREL_INIT", R"VAR()VAR");
	print(1, "STRING", "CMAKE_EXE_LINKER_FLAGS_RELEASE", R"VAR()VAR");
	print(0, "", "CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT", R"VAR()VAR");
	print(1, "STRING", "CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO", R"VAR()VAR");
	print(0, "", "CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO_INIT", R"VAR()VAR");
	print(0, "", "CMAKE_EXE_LINK_DYNAMIC_CXX_FLAGS", R"VAR(-Wl,-Bdynamic)VAR");
	print(0, "", "CMAKE_EXE_LINK_DYNAMIC_C_FLAGS", R"VAR(-Wl,-Bdynamic)VAR");
	print(0, "", "CMAKE_EXE_LINK_STATIC_CXX_FLAGS", R"VAR(-Wl,-Bstatic)VAR");
	print(0, "", "CMAKE_EXE_LINK_STATIC_C_FLAGS", R"VAR(-Wl,-Bstatic)VAR");
	print(1, "BOOL", "CMAKE_EXPORT_COMPILE_COMMANDS", R"VAR(ON)VAR");
	print(1, "BOOL", "CMAKE_EXPORT_COMPILE_COMMANDS", R"VAR(ON)VAR");
	print(0, "INTERNAL", "CMAKE_EXTRA_GENERATOR", R"VAR()VAR");
	print(0, "", "CMAKE_FILES_DIRECTORY", R"VAR(/CMakeFiles)VAR");
	print(0, "", "CMAKE_FIND_FRAMEWORK", R"VAR(LAST)VAR");
	print(0, "", "CMAKE_FIND_LIBRARY_PREFIXES", R"VAR(lib)VAR");
	print(0, "", "CMAKE_FIND_LIBRARY_SUFFIXES", R"VAR(.so;.a)VAR");
	print(0, "INTERNAL", "CMAKE_GENERATOR", R"VAR(Unix Makefiles)VAR");
	print(0, "INTERNAL", "CMAKE_GENERATOR_PLATFORM", R"VAR()VAR");
	print(0, "INTERNAL", "CMAKE_GENERATOR_TOOLSET", R"VAR()VAR");
	print(0, "INTERNAL", "CMAKE_HOME_DIRECTORY", R"VAR(/home/jasper/i2HiWi/code/smtrat)VAR");
	print(0, "", "CMAKE_HOST_SYSTEM", R"VAR(Linux-4.15.0-45-generic)VAR");
	print(0, "", "CMAKE_HOST_SYSTEM_NAME", R"VAR(Linux)VAR");
	print(0, "", "CMAKE_HOST_SYSTEM_PROCESSOR", R"VAR(x86_64)VAR");
	print(0, "", "CMAKE_HOST_SYSTEM_VERSION", R"VAR(4.15.0-45-generic)VAR");
	print(0, "", "CMAKE_HOST_UNIX", R"VAR(1)VAR");
	print(0, "", "CMAKE_INCLUDE_FLAG_C", R"VAR(-I)VAR");
	print(0, "", "CMAKE_INCLUDE_FLAG_CXX", R"VAR(-I)VAR");
	print(0, "", "CMAKE_INCLUDE_FLAG_C_SEP", R"VAR()VAR");
	print(0, "", "CMAKE_INCLUDE_SYSTEM_FLAG_CXX", R"VAR(-isystem )VAR");
	print(1, "PATH", "CMAKE_INSTALL_BINDIR", R"VAR(bin)VAR");
	print(1, "PATH", "CMAKE_INSTALL_DATADIR", R"VAR()VAR");
	print(1, "PATH", "CMAKE_INSTALL_DATAROOTDIR", R"VAR(share)VAR");
	print(0, "", "CMAKE_INSTALL_DEFAULT_COMPONENT_NAME", R"VAR(Unspecified)VAR");
	print(0, "PATH", "CMAKE_INSTALL_DIR", R"VAR(/usr/local/lib/CMake/smtrat)VAR");
	print(0, "PATH", "CMAKE_INSTALL_DIR", R"VAR(/usr/local/lib/CMake/smtrat)VAR");
	print(1, "PATH", "CMAKE_INSTALL_DOCDIR", R"VAR()VAR");
	print(1, "PATH", "CMAKE_INSTALL_INCLUDEDIR", R"VAR(include)VAR");
	print(1, "PATH", "CMAKE_INSTALL_INFODIR", R"VAR()VAR");
	print(1, "PATH", "CMAKE_INSTALL_LIBDIR", R"VAR(lib)VAR");
	print(1, "PATH", "CMAKE_INSTALL_LIBEXECDIR", R"VAR(libexec)VAR");
	print(1, "PATH", "CMAKE_INSTALL_LOCALEDIR", R"VAR()VAR");
	print(1, "PATH", "CMAKE_INSTALL_LOCALSTATEDIR", R"VAR(var)VAR");
	print(1, "PATH", "CMAKE_INSTALL_MANDIR", R"VAR()VAR");
	print(1, "PATH", "CMAKE_INSTALL_OLDINCLUDEDIR", R"VAR(/usr/include)VAR");
	print(0, "PATH", "CMAKE_INSTALL_PREFIX", R"VAR(/usr/local)VAR");
	print(1, "PATH", "CMAKE_INSTALL_RUNSTATEDIR", R"VAR()VAR");
	print(1, "PATH", "CMAKE_INSTALL_SBINDIR", R"VAR(sbin)VAR");
	print(1, "PATH", "CMAKE_INSTALL_SHAREDSTATEDIR", R"VAR(com)VAR");
	print(0, "INTERNAL", "CMAKE_INSTALL_SO_NO_EXE", R"VAR(1)VAR");
	print(1, "PATH", "CMAKE_INSTALL_SYSCONFDIR", R"VAR(etc)VAR");
	print(0, "", "CMAKE_INTERNAL_PLATFORM_ABI", R"VAR(ELF)VAR");
	print(0, "", "CMAKE_LIBRARY_ARCHITECTURE", R"VAR(x86_64-linux-gnu)VAR");
	print(0, "", "CMAKE_LIBRARY_ARCHITECTURE_REGEX", R"VAR([a-z0-9_]+(-[a-z0-9_]+)?-linux-gnu[a-z0-9_]*)VAR");
	print(0, "", "CMAKE_LIBRARY_PATH_FLAG", R"VAR(-L)VAR");
	print(0, "", "CMAKE_LIBRARY_PATH_TERMINATOR", R"VAR()VAR");
	print(1, "FILEPATH", "CMAKE_LINKER", R"VAR(/usr/bin/ld)VAR");
	print(1, "FILEPATH", "CMAKE_LINKER", R"VAR(/usr/bin/ld)VAR");
	print(0, "", "CMAKE_LINK_LIBRARY_FLAG", R"VAR(-l)VAR");
	print(0, "", "CMAKE_LINK_LIBRARY_SUFFIX", R"VAR()VAR");
	print(0, "", "CMAKE_MAJOR_VERSION", R"VAR(3)VAR");
	print(1, "FILEPATH", "CMAKE_MAKE_PROGRAM", R"VAR(/usr/bin/make)VAR");
	print(0, "", "CMAKE_MATCH_0", R"VAR(18.11)VAR");
	print(0, "", "CMAKE_MATCH_1", R"VAR()VAR");
	print(0, "", "CMAKE_MATCH_COUNT", R"VAR(0)VAR");
	print(0, "", "CMAKE_MINIMUM_REQUIRED_VERSION", R"VAR(3.7)VAR");
	print(0, "", "CMAKE_MINOR_VERSION", R"VAR(10)VAR");
	print(1, "STRING", "CMAKE_MODULE_LINKER_FLAGS", R"VAR()VAR");
	print(1, "STRING", "CMAKE_MODULE_LINKER_FLAGS_DEBUG", R"VAR()VAR");
	print(0, "", "CMAKE_MODULE_LINKER_FLAGS_DEBUG_INIT", R"VAR()VAR");
	print(0, "", "CMAKE_MODULE_LINKER_FLAGS_INIT", R"VAR()VAR");
	print(1, "STRING", "CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL", R"VAR()VAR");
	print(0, "", "CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL_INIT", R"VAR()VAR");
	print(1, "STRING", "CMAKE_MODULE_LINKER_FLAGS_RELEASE", R"VAR()VAR");
	print(0, "", "CMAKE_MODULE_LINKER_FLAGS_RELEASE_INIT", R"VAR()VAR");
	print(1, "STRING", "CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO", R"VAR()VAR");
	print(0, "", "CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO_INIT", R"VAR()VAR");
	print(0, "", "CMAKE_MODULE_PATH", R"VAR(/home/jasper/i2HiWi/code/smtrat/cmake)VAR");
	print(1, "FILEPATH", "CMAKE_NM", R"VAR(/usr/bin/nm)VAR");
	print(0, "INTERNAL", "CMAKE_NUMBER_OF_MAKEFILES", R"VAR(48)VAR");
	print(1, "FILEPATH", "CMAKE_OBJCOPY", R"VAR(/usr/bin/objcopy)VAR");
	print(1, "FILEPATH", "CMAKE_OBJDUMP", R"VAR(/usr/bin/objdump)VAR");
	print(0, "", "CMAKE_PARENT_LIST_FILE", R"VAR(/home/jasper/i2HiWi/code/smtrat/src/smtrat-common/CMakeLists.txt)VAR");
	print(0, "", "CMAKE_PATCH_VERSION", R"VAR(2)VAR");
	print(0, "", "CMAKE_PLATFORM_IMPLICIT_LINK_DIRECTORIES", R"VAR(/lib;/lib32;/lib64;/usr/lib;/usr/lib32;/usr/lib64)VAR");
	print(0, "", "CMAKE_PLATFORM_INFO_DIR", R"VAR(/home/jasper/i2HiWi/code/smtrat/build/CMakeFiles/3.10.2)VAR");
	print(0, "INTERNAL", "CMAKE_PLATFORM_INFO_INITIALIZED", R"VAR(1)VAR");
	print(0, "", "CMAKE_PLATFORM_USES_PATH_WHEN_NO_SONAME", R"VAR(1)VAR");
	print(0, "STATIC", "CMAKE_PROJECT_NAME", R"VAR(smtrat)VAR");
	print(1, "FILEPATH", "CMAKE_RANLIB", R"VAR(/usr/bin/ranlib)VAR");
	print(1, "FILEPATH", "CMAKE_RANLIB", R"VAR(/usr/bin/ranlib)VAR");
	print(0, "INTERNAL", "CMAKE_ROOT", R"VAR(/usr/share/cmake-3.10)VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_CREATE_CXX_FLAGS", R"VAR(-shared)VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS", R"VAR(-shared)VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_CXX_FLAGS", R"VAR(-fPIC)VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_C_FLAGS", R"VAR()VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS", R"VAR(-rdynamic)VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_LINK_C_FLAGS", R"VAR()VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_LINK_DYNAMIC_CXX_FLAGS", R"VAR(-Wl,-Bdynamic)VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_LINK_DYNAMIC_C_FLAGS", R"VAR(-Wl,-Bdynamic)VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_LINK_STATIC_CXX_FLAGS", R"VAR(-Wl,-Bstatic)VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_LINK_STATIC_C_FLAGS", R"VAR(-Wl,-Bstatic)VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_PREFIX", R"VAR(lib)VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_RPATH_LINK_CXX_FLAG", R"VAR(-Wl,-rpath-link,)VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_RPATH_LINK_C_FLAG", R"VAR(-Wl,-rpath-link,)VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_RUNTIME_CXX_FLAG", R"VAR(-Wl,-rpath,)VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_RUNTIME_CXX_FLAG_SEP", R"VAR(:)VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG", R"VAR(-Wl,-rpath,)VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG_SEP", R"VAR(:)VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_SONAME_CXX_FLAG", R"VAR(-Wl,-soname,)VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_SONAME_C_FLAG", R"VAR(-Wl,-soname,)VAR");
	print(0, "", "CMAKE_SHARED_LIBRARY_SUFFIX", R"VAR(.so)VAR");
	print(1, "STRING", "CMAKE_SHARED_LINKER_FLAGS", R"VAR()VAR");
	print(1, "STRING", "CMAKE_SHARED_LINKER_FLAGS_DEBUG", R"VAR()VAR");
	print(0, "", "CMAKE_SHARED_LINKER_FLAGS_DEBUG_INIT", R"VAR()VAR");
	print(0, "", "CMAKE_SHARED_LINKER_FLAGS_INIT", R"VAR()VAR");
	print(1, "STRING", "CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL", R"VAR()VAR");
	print(0, "", "CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL_INIT", R"VAR()VAR");
	print(1, "STRING", "CMAKE_SHARED_LINKER_FLAGS_RELEASE", R"VAR()VAR");
	print(0, "", "CMAKE_SHARED_LINKER_FLAGS_RELEASE_INIT", R"VAR()VAR");
	print(1, "STRING", "CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO", R"VAR()VAR");
	print(0, "", "CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO_INIT", R"VAR()VAR");
	print(0, "", "CMAKE_SHARED_MODULE_CREATE_CXX_FLAGS", R"VAR(-shared)VAR");
	print(0, "", "CMAKE_SHARED_MODULE_CXX_FLAGS", R"VAR(-fPIC)VAR");
	print(0, "", "CMAKE_SHARED_MODULE_LINK_DYNAMIC_CXX_FLAGS", R"VAR(-Wl,-Bdynamic)VAR");
	print(0, "", "CMAKE_SHARED_MODULE_LINK_DYNAMIC_C_FLAGS", R"VAR(-Wl,-Bdynamic)VAR");
	print(0, "", "CMAKE_SHARED_MODULE_LINK_STATIC_CXX_FLAGS", R"VAR(-Wl,-Bstatic)VAR");
	print(0, "", "CMAKE_SHARED_MODULE_LINK_STATIC_C_FLAGS", R"VAR(-Wl,-Bstatic)VAR");
	print(0, "", "CMAKE_SHARED_MODULE_PREFIX", R"VAR(lib)VAR");
	print(0, "", "CMAKE_SHARED_MODULE_SUFFIX", R"VAR(.so)VAR");
	print(0, "", "CMAKE_SIZEOF_VOID_P", R"VAR(8)VAR");
	print(1, "BOOL", "CMAKE_SKIP_INSTALL_RPATH", R"VAR(NO)VAR");
	print(1, "BOOL", "CMAKE_SKIP_RPATH", R"VAR(NO)VAR");
	print(0, "", "CMAKE_SOURCE_DIR", R"VAR(/home/jasper/i2HiWi/code/smtrat)VAR");
	print(0, "", "CMAKE_STATIC_LIBRARY_PREFIX", R"VAR(lib)VAR");
	print(0, "", "CMAKE_STATIC_LIBRARY_SUFFIX", R"VAR(.a)VAR");
	print(1, "STRING", "CMAKE_STATIC_LINKER_FLAGS", R"VAR()VAR");
	print(1, "STRING", "CMAKE_STATIC_LINKER_FLAGS_DEBUG", R"VAR()VAR");
	print(0, "", "CMAKE_STATIC_LINKER_FLAGS_DEBUG_INIT", R"VAR()VAR");
	print(0, "", "CMAKE_STATIC_LINKER_FLAGS_INIT", R"VAR()VAR");
	print(1, "STRING", "CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL", R"VAR()VAR");
	print(0, "", "CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL_INIT", R"VAR()VAR");
	print(1, "STRING", "CMAKE_STATIC_LINKER_FLAGS_RELEASE", R"VAR()VAR");
	print(0, "", "CMAKE_STATIC_LINKER_FLAGS_RELEASE_INIT", R"VAR()VAR");
	print(1, "STRING", "CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO", R"VAR()VAR");
	print(0, "", "CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO_INIT", R"VAR()VAR");
	print(1, "FILEPATH", "CMAKE_STRIP", R"VAR(/usr/bin/strip)VAR");
	print(0, "", "CMAKE_SYSTEM", R"VAR(Linux-4.15.0-45-generic)VAR");
	print(0, "", "CMAKE_SYSTEM_INCLUDE_PATH", R"VAR(/usr/include/X11)VAR");
	print(0, "", "CMAKE_SYSTEM_INFO_FILE", R"VAR(Platform/Linux)VAR");
	print(0, "", "CMAKE_SYSTEM_LIBRARY_PATH", R"VAR(/usr/lib/X11)VAR");
	print(0, "", "CMAKE_SYSTEM_LOADED", R"VAR(1)VAR");
	print(0, "", "CMAKE_SYSTEM_NAME", R"VAR(Linux)VAR");
	print(0, "", "CMAKE_SYSTEM_PREFIX_PATH", R"VAR(/usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt)VAR");
	print(0, "", "CMAKE_SYSTEM_PROCESSOR", R"VAR(x86_64)VAR");
	print(0, "", "CMAKE_SYSTEM_SPECIFIC_INFORMATION_LOADED", R"VAR(1)VAR");
	print(0, "", "CMAKE_SYSTEM_SPECIFIC_INITIALIZE_LOADED", R"VAR(1)VAR");
	print(0, "", "CMAKE_SYSTEM_VERSION", R"VAR(4.15.0-45-generic)VAR");
	print(0, "", "CMAKE_TWEAK_VERSION", R"VAR(0)VAR");
	print(0, "INTERNAL", "CMAKE_UNAME", R"VAR(/bin/uname)VAR");
	print(1, "BOOL", "CMAKE_VERBOSE_MAKEFILE", R"VAR(FALSE)VAR");
	print(0, "", "CMAKE_VERSION", R"VAR(3.10.2)VAR");
	print(0, "", "DEF_INSTALL_CMAKE_DIR", R"VAR(lib/CMake/smtrat)VAR");
	print(0, "BOOL", "DEVELOPER", R"VAR(ON)VAR");
	print(1, "FILEPATH", "DVIPDF_CONVERTER", R"VAR(/usr/bin/dvipdfm)VAR");
	print(1, "FILEPATH", "DVIPS_CONVERTER", R"VAR(/usr/bin/dvips)VAR");
	print(0, "", "DYNAMIC_EXT", R"VAR(.so)VAR");
	print(0, "BOOL", "ENABLE_TESTING", R"VAR(OFF)VAR");
	print(0, "PATH", "EXECUTABLE_OUTPUT_PATH", R"VAR(/home/jasper/i2HiWi/code/smtrat/build)VAR");
	print(0, "PATH", "EXECUTABLE_OUTPUT_PATH", R"VAR(/home/jasper/i2HiWi/code/smtrat/build)VAR");
	print(0, "BOOL", "EXPORT_TO_CMAKE", R"VAR(ON)VAR");
	print(0, "INTERNAL", "FIND_PACKAGE_MESSAGE_DETAILS_LATEX", R"VAR([/usr/bin/latex][c ][v()])VAR");
	print(0, "INTERNAL", "FIND_PACKAGE_MESSAGE_DETAILS_PythonInterp", R"VAR([/usr/bin/python3][v3.6.7(3)])VAR");
	print(0, "BOOL", "FORCE_SHIPPED_RESOURCES", R"VAR(OFF)VAR");
	print(0, "", "GIT_REFSPEC", R"VAR(refs/heads/mcsat-dynamic-varorder)VAR");
	print(0, "", "GIT_SHA1", R"VAR(cb64a52d333129f361906d9d655054eb1cf642c8)VAR");
	print(1, "FILEPATH", "HTLATEX_COMPILER", R"VAR(/usr/bin/htlatex)VAR");
	print(0, "", "INCLUDE_INSTALL_DIR", R"VAR(/usr/local/)VAR");
	print(1, "FILEPATH", "LATEX2HTML_CONVERTER", R"VAR(LATEX2HTML_CONVERTER-NOTFOUND)VAR");
	print(1, "FILEPATH", "LATEX_COMPILER", R"VAR(/usr/bin/latex)VAR");
	print(0, "FILEPATH", "LIBSSH", R"VAR(LIBSSH-NOTFOUND)VAR");
	print(0, "FILEPATH", "LIBSSH_THREADS", R"VAR(LIBSSH_THREADS-NOTFOUND)VAR");
	print(0, "", "LIB_INSTALL_DIR", R"VAR(/usr/local/)VAR");
	print(0, "BOOL", "LOGGING", R"VAR(OFF)VAR");
	print(0, "BOOL", "LOGGING_CARL", R"VAR(OFF)VAR");
	print(1, "FILEPATH", "LUALATEX_COMPILER", R"VAR(/usr/bin/lualatex)VAR");
	print(1, "FILEPATH", "MAKEINDEX_COMPILER", R"VAR(/usr/bin/makeindex)VAR");
	print(0, "STRING", "NEWCAD_BACKTRACKING", R"VAR(UNORDERED)VAR");
	print(0, "STRING", "NEWCAD_INCREMENTALITY", R"VAR(FULL)VAR");
	print(0, "STRING", "NEWCAD_MISHEURISTIC", R"VAR(GREEDY)VAR");
	print(0, "", "PACKAGE_PREFIX_DIR", R"VAR(/usr/local)VAR");
	print(1, "FILEPATH", "PDFLATEX_COMPILER", R"VAR(/usr/bin/pdflatex)VAR");
	print(1, "FILEPATH", "PDFTOPS_CONVERTER", R"VAR(/usr/bin/pdftops)VAR");
	print(0, "", "PROJECT_BINARY_DIR", R"VAR(/home/jasper/i2HiWi/code/smtrat/build)VAR");
	print(0, "", "PROJECT_DESCRIPTION", R"VAR(Toolbox for Strategic and Parallel Satisfiability-Modulo-Theories Solving)VAR");
	print(0, "", "PROJECT_FULLNAME", R"VAR(SMT-RAT)VAR");
	print(0, "", "PROJECT_NAME", R"VAR(smtrat)VAR");
	print(0, "", "PROJECT_SOURCE_DIR", R"VAR(/home/jasper/i2HiWi/code/smtrat)VAR");
	print(0, "", "PROJECT_VERSION", R"VAR(18.12.122)VAR");
	print(0, "", "PROJECT_VERSION_FULL", R"VAR(18.12.122-gcb64a52d)VAR");
	print(0, "", "PROJECT_VERSION_LIB", R"VAR(18.12)VAR");
	print(0, "", "PROJECT_VERSION_MAJOR", R"VAR(18)VAR");
	print(0, "", "PROJECT_VERSION_MINOR", R"VAR(12)VAR");
	print(0, "", "PROJECT_VERSION_PATCH", R"VAR(122)VAR");
	print(1, "FILEPATH", "PS2PDF_CONVERTER", R"VAR(/usr/bin/ps2pdf14)VAR");
	print(1, "FILEPATH", "PYTHON_EXECUTABLE", R"VAR(/usr/bin/python3)VAR");
	print(0, "", "RUN_CONFIGURE", R"VAR(ON)VAR");
	print(0, "BOOL", "SMTRAT_DEVOPTION_MeasureTime", R"VAR(OFF)VAR");
	print(0, "BOOL", "SMTRAT_DEVOPTION_Statistics", R"VAR(ON)VAR");
	print(0, "BOOL", "SMTRAT_DEVOPTION_Validation", R"VAR(OFF)VAR");
	print(0, "", "SMTRAT_MANUAL_PATH", R"VAR(/home/jasper/i2HiWi/code/smtrat/manual/manual_smtrat-18.12.122.pdf)VAR");
	print(0, "", "SMTRAT_MODULES_PATH", R"VAR(/home/jasper/i2HiWi/code/smtrat/src/lib/modules)VAR");
	print(0, "BOOL", "SMTRAT_STRAT_Factorization", R"VAR(ON)VAR");
	print(0, "BOOL", "SMTRAT_STRAT_PARALLEL_MODE", R"VAR(OFF)VAR");
	print(0, "STRING", "SMTRAT_Strategy", R"VAR(MCSATFMVSOC)VAR");
	print(0, "BOOL", "SMTRAT_VS_VARIABLEBOUNDS", R"VAR(ON)VAR");
	print(0, "BOOL", "STATICLIB_SWITCH", R"VAR(OFF)VAR");
	print(0, "", "STATIC_EXT", R"VAR(.a)VAR");
	print(0, "", "UNIX", R"VAR(1)VAR");
	print(0, "BOOL", "USE_BOOST_REGEX", R"VAR(OFF)VAR");
	print(0, "BOOL", "USE_COCOA", R"VAR(OFF)VAR");
	print(0, "BOOL", "USE_COTIRE", R"VAR(OFF)VAR");
	print(0, "BOOL", "USE_GINAC", R"VAR(OFF)VAR");
	print(1, "FILEPATH", "XELATEX_COMPILER", R"VAR(/usr/bin/xelatex)VAR");
	print(1, "FILEPATH", "XINDY_COMPILER", R"VAR(XINDY_COMPILER-NOTFOUND)VAR");
	print(0, "", "_CMAKE_CXX_IPO_MAY_BE_SUPPORTED_BY_COMPILER", R"VAR(YES)VAR");
	print(0, "", "_CMAKE_CXX_IPO_SUPPORTED_BY_CMAKE", R"VAR(YES)VAR");
	print(0, "", "_CMAKE_INSTALL_DIR", R"VAR(/usr)VAR");
	print(0, "", "_ExternalProject_SELF", R"VAR(/usr/share/cmake-3.10/Modules/ExternalProject.cmake)VAR");
	print(0, "", "_ExternalProject_SELF_DIR", R"VAR(/usr/share/cmake-3.10/Modules)VAR");
	print(0, "INTERNAL", "_GNUInstallDirs_LAST_CMAKE_INSTALL_PREFIX", R"VAR(/usr/local)VAR");
	print(0, "", "_INCLUDED_FILE", R"VAR(/usr/share/cmake-3.10/Modules/Platform/Linux-GNU-CXX.cmake)VAR");
	print(0, "", "_INCLUDED_SYSTEM_INFO_FILE", R"VAR(/usr/share/cmake-3.10/Modules/Platform/Linux.cmake)VAR");
	print(0, "", "_IN_TC", R"VAR(0)VAR");
	print(0, "", "__COMPILER_CMAKE_COMMON_COMPILER_MACROS", R"VAR(1)VAR");
	print(0, "", "__COMPILER_GNU", R"VAR(1)VAR");
	print(0, "", "__LINUX_COMPILER_GNU", R"VAR(1)VAR");
	print(0, "", "__UNIX_PATHS_INCLUDED", R"VAR(1)VAR");
	print(0, "", "__get_git_revision_description", R"VAR(YES)VAR");
	print(0, "", "__lto_flags", R"VAR(-flto;-fno-fat-lto-objects)VAR");
	print(0, "", "_ep_documentation_line_count", R"VAR(857)VAR");
	print(0, "", "_ep_func", R"VAR(ExternalProject_Add_StepDependencies)VAR");
	print(0, "", "_ep_hash_algos", R"VAR(MD5|SHA1|SHA224|SHA256|SHA384|SHA512|SHA3_224|SHA3_256|SHA3_384|SHA3_512)VAR");
	print(0, "", "_ep_hash_regex", R"VAR(^(MD5|SHA1|SHA224|SHA256|SHA384|SHA512|SHA3_224|SHA3_256|SHA3_384|SHA3_512)=([0-9A-Fa-f]+)$)VAR");
	print(0, "", "_ep_key", R"VAR(USES_TERMINAL)VAR");
	print(0, "", "_ep_keywords_ExternalProject_Add", R"VAR(^(PREFIX|TMP_DIR|STAMP_DIR|DOWNLOAD_DIR|SOURCE_DIR|BINARY_DIR|INSTALL_DIR|DOWNLOAD_COMMAND|URL|URL_HASH|URL_MD5|DOWNLOAD_NAME|DOWNLOAD_NO_EXTRACT|DOWNLOAD_NO_PROGRESS|TIMEOUT|HTTP_USERNAME|HTTP_PASSWORD|HTTP_HEADER|TLS_VERIFY|TLS_CAINFO|GIT_REPOSITORY|GIT_TAG|GIT_REMOTE_NAME|GIT_SUBMODULES|GIT_SHALLOW|GIT_PROGRESS|GIT_CONFIG|SVN_REPOSITORY|SVN_REVISION|SVN_USERNAME|SVN_PASSWORD|SVN_TRUST_CERT|HG_REPOSITORY|HG_TAG|CVS_REPOSITORY|CVS_MODULE|CVS_TAG|UPDATE_COMMAND|UPDATE_DISCONNECTED|PATCH_COMMAND|CONFIGURE_COMMAND|CMAKE_COMMAND|CMAKE_GENERATOR|CMAKE_GENERATOR_PLATFORM|CMAKE_GENERATOR_TOOLSET|CMAKE_ARGS|CMAKE_CACHE_ARGS|CMAKE_CACHE_DEFAULT_ARGS|SOURCE_SUBDIR|BUILD_COMMAND|BUILD_IN_SOURCE|BUILD_ALWAYS|BUILD_BYPRODUCTS|INSTALL_COMMAND|TEST_COMMAND|TEST_BEFORE_INSTALL|TEST_AFTER_INSTALL|TEST_EXCLUDE_FROM_MAIN|LOG_DOWNLOAD|LOG_UPDATE|LOG_CONFIGURE|LOG_BUILD|LOG_INSTALL|LOG_TEST|USES_TERMINAL_DOWNLOAD|USES_TERMINAL_UPDATE|USES_TERMINAL_CONFIGURE|USES_TERMINAL_BUILD|USES_TERMINAL_INSTALL|USES_TERMINAL_TEST|DEPENDS|EXCLUDE_FROM_ALL|STEP_TARGETS|INDEPENDENT_STEP_TARGETS|LIST_SEPARATOR)$)VAR");
	print(0, "", "_ep_keywords_ExternalProject_Add_Step", R"VAR(^(COMMAND|COMMENT|DEPENDEES|DEPENDERS|DEPENDS|BYPRODUCTS|ALWAYS|EXCLUDE_FROM_MAIN|WORKING_DIRECTORY|LOG|USES_TERMINAL)$)VAR");
	print(0, "", "_ep_keywords_ExternalProject_Add_StepDependencies", R"VAR(^()$)VAR");
	print(0, "", "_ep_keywords_ExternalProject_Add_StepTargets", R"VAR(^()$)VAR");
	print(0, "", "_ep_keywords_ExternalProject_Get_Property", R"VAR(^()$)VAR");
	print(0, "", "_expectedTarget", R"VAR()VAR");
	print(0, "", "_gitdescmoddir", R"VAR(/home/jasper/i2HiWi/code/smtrat/cmake)VAR");
	print(0, "", "c", R"VAR()VAR");
	print(0, "", "carl_CMAKE_DIR", R"VAR(/home/jasper/i2HiWi/code/carl/build)VAR");
	print(0, "", "carl_CONFIG", R"VAR(/home/jasper/i2HiWi/code/carl/build/carlConfig.cmake)VAR");
	print(0, "", "carl_CONSIDERED_CONFIGS", R"VAR(/home/jasper/i2HiWi/code/carl/build/carlConfig.cmake)VAR");
	print(0, "", "carl_CONSIDERED_VERSIONS", R"VAR(19.01.2)VAR");
	print(0, "PATH", "carl_DIR", R"VAR(/home/jasper/i2HiWi/code/carl/build)VAR");
	print(0, "", "carl_FOUND", R"VAR(1)VAR");
	print(0, "", "carl_INCLUDE_DIR", R"VAR(/home/jasper/i2HiWi/code/carl/src)VAR");
	print(0, "", "carl_LIBRARIES", R"VAR(carl-shared)VAR");
	print(0, "", "carl_MINORMONTHVERSION", R"VAR(01)VAR");
	print(0, "", "carl_MINORYEARVERSION", R"VAR(19)VAR");
	print(0, "", "carl_VERSION", R"VAR(19.01.2-ga2863c7a)VAR");
	print(0, "", "carl_VERSION_COUNT", R"VAR(3)VAR");
	print(0, "", "carl_VERSION_MAJOR", R"VAR(19)VAR");
	print(0, "", "carl_VERSION_MINOR", R"VAR(01)VAR");
	print(0, "", "carl_VERSION_TWEAK", R"VAR(0)VAR");
	print(0, "", "comp", R"VAR()VAR");
	print(0, "", "f", R"VAR()VAR");
	print(0, "STATIC", "lib_smtrat_LIB_DEPENDS", R"VAR(general;carl-shared;general;smtrat-common-shared;)VAR");
	print(0, "", "libraries", R"VAR(carl-shared;Boost_SHARED)VAR");
	print(0, "", "line", R"VAR()VAR");
	print(0, "", "lines", R"VAR(.. command:: ExternalProject_Add;    ``PREFIX <dir>``;    ``TMP_DIR <dir>``;    ``STAMP_DIR <dir>``;    ``DOWNLOAD_DIR <dir>``;    ``SOURCE_DIR <dir>``;    ``BINARY_DIR <dir>``;    ``INSTALL_DIR <dir>``;    ``DOWNLOAD_COMMAND <cmd>...``;      ``URL <url1> [<url2>...]``;      ``URL_HASH ALGO=<value>``;      ``URL_MD5 <md5>``;      ``DOWNLOAD_NAME <fname>``;      ``DOWNLOAD_NO_EXTRACT <bool>``;      ``DOWNLOAD_NO_PROGRESS <bool>``;      ``TIMEOUT <seconds>``;      ``HTTP_USERNAME <username>``;      ``HTTP_PASSWORD <password>``;      ``HTTP_HEADER <header1> [<header2>...]``;      ``TLS_VERIFY <bool>``;      ``TLS_CAINFO <file>``;      ``GIT_REPOSITORY <url>``;      ``GIT_TAG <tag>``;      ``GIT_REMOTE_NAME <name>``;      ``GIT_SUBMODULES <module>...``;      ``GIT_SHALLOW <bool>``;      ``GIT_PROGRESS <bool>``;      ``GIT_CONFIG <option1> [<option2>...]``;      ``SVN_REPOSITORY <url>``;      ``SVN_REVISION -r<rev>``;      ``SVN_USERNAME <username>``;      ``SVN_PASSWORD <password>``;      ``SVN_TRUST_CERT <bool>``;      ``HG_REPOSITORY <url>``;      ``HG_TAG <tag>``;      ``CVS_REPOSITORY <cvsroot>``;      ``CVS_MODULE <mod>``;      ``CVS_TAG <tag>``;    ``UPDATE_COMMAND <cmd>...``;    ``UPDATE_DISCONNECTED <bool>``;    ``PATCH_COMMAND <cmd>...``;    ``CONFIGURE_COMMAND <cmd>...``;    ``CMAKE_COMMAND /.../cmake``;    ``CMAKE_GENERATOR <gen>``;    ``CMAKE_GENERATOR_PLATFORM <platform>``;    ``CMAKE_GENERATOR_TOOLSET <toolset>``;    ``CMAKE_ARGS <arg>...``;    ``CMAKE_CACHE_ARGS <arg>...``;    ``CMAKE_CACHE_DEFAULT_ARGS <arg>...``;    ``SOURCE_SUBDIR <dir>``;    ``BUILD_COMMAND <cmd>...``;    ``BUILD_IN_SOURCE <bool>``;    ``BUILD_ALWAYS <bool>``;    ``BUILD_BYPRODUCTS <file>...``;    ``INSTALL_COMMAND <cmd>...``;    ``TEST_COMMAND <cmd>...``;    ``TEST_BEFORE_INSTALL <bool>``;    ``TEST_AFTER_INSTALL <bool>``;    ``TEST_EXCLUDE_FROM_MAIN <bool>``;    ``LOG_DOWNLOAD <bool>``;    ``LOG_UPDATE <bool>``;    ``LOG_CONFIGURE <bool>``;    ``LOG_BUILD <bool>``;    ``LOG_INSTALL <bool>``;    ``LOG_TEST <bool>``;    ``USES_TERMINAL_DOWNLOAD <bool>``;    ``USES_TERMINAL_UPDATE <bool>``;    ``USES_TERMINAL_CONFIGURE <bool>``;    ``USES_TERMINAL_BUILD <bool>``;    ``USES_TERMINAL_INSTALL <bool>``;    ``USES_TERMINAL_TEST <bool>``;    ``DEPENDS <targets>...``;    ``EXCLUDE_FROM_ALL <bool>``;    ``STEP_TARGETS <step-target>...``;    ``INDEPENDENT_STEP_TARGETS <step-target>...``;    ``LIST_SEPARATOR <sep>``;    ``COMMAND <cmd>...``;.. command:: ExternalProject_Get_Property;.. command:: ExternalProject_Add_Step;  ``COMMAND <cmd>...``;  ``COMMENT "<text>..."``;  ``DEPENDEES <step>...``;  ``DEPENDERS <step>...``;  ``DEPENDS <file>...``;  ``BYPRODUCTS <file>...``;  ``ALWAYS <bool>``;  ``EXCLUDE_FROM_MAIN <bool>``;  ``WORKING_DIRECTORY <dir>``;  ``LOG <bool>``;  ``USES_TERMINAL <bool>``;.. command:: ExternalProject_Add_StepTargets;.. command:: ExternalProject_Add_StepDependencies)VAR");
	print(0, "", "p", R"VAR()VAR");
	print(0, "STATIC", "smtrat-cad-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;)VAR");
	print(0, "STATIC", "smtrat-cad-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;)VAR");
	print(0, "STATIC", "smtrat-common-shared_LIB_DEPENDS", R"VAR(general;carl-shared;)VAR");
	print(0, "STATIC", "smtrat-common-static_LIB_DEPENDS", R"VAR(general;carl-static;)VAR");
	print(0, "STATIC", "smtrat-mcsat-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-solver-shared;general;smtrat-module-LRAModule-shared;general;smtrat-module-VSModule-shared;)VAR");
	print(0, "STATIC", "smtrat-mcsat-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-solver-static;general;smtrat-module-LRAModule-static;general;smtrat-module-VSModule-static;)VAR");
	print(0, "STATIC", "smtrat-module-BEModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-BEModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-BVModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-BVModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-CADModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-CADModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-CNFerModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-CNFerModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-CSplitModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-CSplitModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-CoCoAGBModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-CoCoAGBModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-CubeLIAModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-CubeLIAModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-EMModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-EMModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-EQModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-EQModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-EQPreprocessingModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-EQPreprocessingModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-ESModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-ESModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-FPPModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;general;smtrat-strategy-PreprocessingOne-shared;)VAR");
	print(0, "STATIC", "smtrat-module-FPPModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;general;smtrat-strategy-PreprocessingOne-static;)VAR");
	print(0, "STATIC", "smtrat-module-FouMoModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-FouMoModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-GBModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-GBModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-GBPPModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-GBPPModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-ICEModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-ICEModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-ICPModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-ICPModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-IncWidthModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-IncWidthModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-IntBlastModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;general;smtrat-strategy-BVSolver-shared;)VAR");
	print(0, "STATIC", "smtrat-module-IntBlastModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;general;smtrat-strategy-BVSolver-static;)VAR");
	print(0, "STATIC", "smtrat-module-IntEqModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-IntEqModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-LRAModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-LRAModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-MCBModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-MCBModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-NewCADModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;general;smtrat-cad-shared;)VAR");
	print(0, "STATIC", "smtrat-module-NewCADModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;general;smtrat-cad-static;)VAR");
	print(0, "STATIC", "smtrat-module-PBGaussModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-PBGaussModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-PBPPModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;general;smtrat-solver-shared;)VAR");
	print(0, "STATIC", "smtrat-module-PBPPModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;general;smtrat-solver-static;)VAR");
	print(0, "STATIC", "smtrat-module-PFEModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-PFEModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-SATModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;general;smtrat-mcsat-shared;)VAR");
	print(0, "STATIC", "smtrat-module-SATModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;general;smtrat-mcsat-static;)VAR");
	print(0, "STATIC", "smtrat-module-STropModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-STropModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-SplitSOSModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-SplitSOSModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-SymmetryModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-SymmetryModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-module-VSModule-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;smtrat-modules-shared;)VAR");
	print(0, "STATIC", "smtrat-module-VSModule-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;smtrat-modules-static;)VAR");
	print(0, "STATIC", "smtrat-modules-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;)VAR");
	print(0, "STATIC", "smtrat-modules-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;)VAR");
	print(0, "STATIC", "smtrat-qe-shared_LIB_DEPENDS", R"VAR(general;lib_smtrat;general;smtrat-common-shared;)VAR");
	print(0, "STATIC", "smtrat-qe-static_LIB_DEPENDS", R"VAR(general;lib_smtrat;general;smtrat-common-static;)VAR");
	print(0, "STATIC", "smtrat-solver-shared_LIB_DEPENDS", R"VAR(general;lib_smtrat;general;smtrat-common-shared;)VAR");
	print(0, "STATIC", "smtrat-solver-static_LIB_DEPENDS", R"VAR(general;lib_smtrat;general;smtrat-common-static;)VAR");
	print(0, "STATIC", "smtrat-strategies-shared_LIB_DEPENDS", R"VAR(general;smtrat-solver-shared;)VAR");
	print(0, "STATIC", "smtrat-strategies-static_LIB_DEPENDS", R"VAR(general;smtrat-solver-static;)VAR");
	print(0, "STATIC", "smtrat-unsat-cores-shared_LIB_DEPENDS", R"VAR(general;smtrat-common-shared;general;carl-shared;)VAR");
	print(0, "STATIC", "smtrat-unsat-cores-static_LIB_DEPENDS", R"VAR(general;smtrat-common-static;general;carl-static;)VAR");
	print(0, "STATIC", "smtrat-wrapper-shared_LIB_DEPENDS", R"VAR(general;lib_smtrat;general;smtrat-common-shared;general;smtrat-modules-shared;general;smtrat-strategies-shared;)VAR");
	print(0, "STATIC", "smtrat-wrapper-static_LIB_DEPENDS", R"VAR(general;lib_smtrat;general;smtrat-common-static;general;smtrat-modules-static;general;smtrat-strategies-static;)VAR");
	print(0, "STATIC", "smtrat_BINARY_DIR", R"VAR(/home/jasper/i2HiWi/code/smtrat/build)VAR");
	print(0, "", "smtrat_DESCRIPTION", R"VAR(Toolbox for Strategic and Parallel Satisfiability-Modulo-Theories Solving)VAR");
	print(0, "BOOL", "smtrat_DOC_CREATE_PDF", R"VAR(ON)VAR");
	print(0, "", "smtrat_NAME", R"VAR(SMT-RAT)VAR");
	print(0, "STATIC", "smtrat_SOURCE_DIR", R"VAR(/home/jasper/i2HiWi/code/smtrat)VAR");
	print(0, "", "t", R"VAR()VAR");
	print(0, "", "type", R"VAR()VAR");
	print(0, "", "var", R"VAR(CMAKE_INSTALL_DIR)VAR");

	return os;
}

}
